"""empty message

Revision ID: 1b596430f2b8
Revises: None
Create Date: 2014-03-16 19:42:46.704839

"""

# revision identifiers, used by Alembic.
revision = '1b596430f2b8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
